{
	"title": "CVE-2018-10855",
	"cve": "CVE-2018-10855",
	"notes": [
		{
			"type": "Description",
			"text": "Ansible 2.5 prior to 2.5.5, and 2.4 prior to 2.4.5, do not honor the no_log task flag for failed tasks. When the no_log flag has been used to protect sensitive data passed to a task from being logged, and that task does not run successfully, Ansible will expose sensitive data in log files and on the terminal of the user running Ansible."
		},
		{
			"title": "Published",
			"type": "Other",
			"text": "2018-07-02"
		},
		{
			"title": "Modified",
			"type": "Other",
			"text": "2019-07-24"
		}
	],
	"references": [
		{
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10855",
			"description": "CONFIRM:https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10855"
		},
		{
			"url": "https://www.debian.org/security/2019/dsa-4396",
			"description": "DEBIAN:DSA-4396"
		},
		{
			"url": "https://access.redhat.com/errata/RHBA-2018:3788",
			"description": "REDHAT:RHBA-2018:3788"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2018:1948",
			"description": "REDHAT:RHSA-2018:1948"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2018:1949",
			"description": "REDHAT:RHSA-2018:1949"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2018:2022",
			"description": "REDHAT:RHSA-2018:2022"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2018:2079",
			"description": "REDHAT:RHSA-2018:2079"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2018:2184",
			"description": "REDHAT:RHSA-2018:2184"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2018:2585",
			"description": "REDHAT:RHSA-2018:2585"
		},
		{
			"url": "https://access.redhat.com/errata/RHSA-2019:0054",
			"description": "REDHAT:RHSA-2019:0054"
		},
		{
			"url": "https://usn.ubuntu.com/4072-1/",
			"description": "UBUNTU:USN-4072-1"
		}
	]
}
