{
	"title": "CVE-2019-14853",
	"cve": "CVE-2019-14853",
	"notes": [
		{
			"type": "Description",
			"text": "An error-handling flaw was found in python-ecdsa before version 0.13.3. During signature decoding, malformed DER signatures could raise unexpected exceptions (or no exceptions at all), which could lead to a denial of service."
		},
		{
			"title": "Published",
			"type": "Other",
			"text": "2019-11-26"
		},
		{
			"title": "Modified",
			"type": "Other",
			"text": "2019-12-18"
		}
	],
	"references": [
		{
			"url": "https://seclists.org/bugtraq/2019/Dec/33",
			"description": "BUGTRAQ:20191218 [SECURITY] [DSA 4588-1] python-ecdsa security update"
		},
		{
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14853",
			"description": "CONFIRM:https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14853"
		},
		{
			"url": "https://www.debian.org/security/2019/dsa-4588",
			"description": "DEBIAN:DSA-4588"
		},
		{
			"url": "https://github.com/warner/python-ecdsa/releases/tag/python-ecdsa-0.13.3",
			"description": "MISC:https://github.com/warner/python-ecdsa/releases/tag/python-ecdsa-0.13.3"
		}
	]
}
