{
	"title": "CVE-2020-28896",
	"cve": "CVE-2020-28896",
	"notes": {
		"description": "Mutt before 2.0.2 and NeoMutt before 2020-11-20 did not ensure that $ssl_force_tls was processed if an IMAP server's initial server response was invalid. The connection was not properly closed, and the code could continue attempting to authenticate. This could result in authentication credentials being exposed on an unencrypted connection, or to a machine-in-the-middle.",
		"published": "2020-11-23",
		"modified": "2021-01-26"
	},
	"references": [
		{
			"url": "https://security.gentoo.org/glsa/202101-32",
			"description": "GENTOO:GLSA-202101-32"
		},
		{
			"url": "https://github.com/neomutt/neomutt/commit/9c36717a3e2af1f2c1b7242035455ec8112b4b06",
			"description": "MISC:https://github.com/neomutt/neomutt/commit/9c36717a3e2af1f2c1b7242035455ec8112b4b06"
		},
		{
			"url": "https://github.com/neomutt/neomutt/releases/tag/20201120",
			"description": "MISC:https://github.com/neomutt/neomutt/releases/tag/20201120"
		},
		{
			"url": "https://gitlab.com/muttmua/mutt/-/commit/04b06aaa3e0cc0022b9b01dbca2863756ebbf59a",
			"description": "MISC:https://gitlab.com/muttmua/mutt/-/commit/04b06aaa3e0cc0022b9b01dbca2863756ebbf59a"
		},
		{
			"url": "https://gitlab.com/muttmua/mutt/-/commit/d92689088dfe80a290ec836e292376e2d9984f8f",
			"description": "MISC:https://gitlab.com/muttmua/mutt/-/commit/d92689088dfe80a290ec836e292376e2d9984f8f"
		},
		{
			"url": "https://lists.debian.org/debian-lts-announce/2020/11/msg00048.html",
			"description": "MLIST:[debian-lts-announce] 20201130 [SECURITY] [DLA 2472-1] mutt security update"
		}
	]
}
