{
  "title": "CVE-2020-15523",
  "cve": "CVE-2020-15523",
  "notes": {
    "description": "In Python 3.6 through 3.6.10, 3.7 through 3.7.8, 3.8 through 3.8.4rc1, and 3.9 through 3.9.0b4 on Windows, a Trojan horse python3.dll might be used in cases where CPython is embedded in a native application. This occurs because python3X.dll may use an invalid search path for python3.dll loading (after Py_SetPath has been used). NOTE: this issue CANNOT occur when using python.exe from a standard (non-embedded) Python installation on Windows.",
    "published": "2020-07-04",
    "modified": "2021-03-12"
  },
  "references": [
    {
      "url": "https://security.netapp.com/advisory/ntap-20210312-0004/",
      "description": "CONFIRM:https://security.netapp.com/advisory/ntap-20210312-0004/"
    },
    {
      "url": "https://bugs.python.org/issue29778",
      "description": "MISC:https://bugs.python.org/issue29778"
    },
    {
      "url": "https://github.com/python/cpython/pull/21297",
      "description": "MISC:https://github.com/python/cpython/pull/21297"
    }
  ]
}
