{
	"title": "CVE-2021-20275",
	"cve": "CVE-2021-20275",
	"notes": [
		{
			"type": "Description",
			"text": "A flaw was found in privoxy before 3.0.32. A invalid read of size two may occur in chunked_body_is_complete() leading to denial of service."
		},
		{
			"title": "Published",
			"type": "Other",
			"text": "2021-03-09"
		},
		{
			"title": "Modified",
			"type": "Other",
			"text": "2021-07-08"
		}
	],
	"references": [
		{
			"url": "https://security.gentoo.org/glsa/202107-16",
			"description": "GENTOO:GLSA-202107-16"
		},
		{
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1936666",
			"description": "MISC:https://bugzilla.redhat.com/show_bug.cgi?id=1936666"
		},
		{
			"url": "https://www.privoxy.org/announce.txt",
			"description": "MISC:https://www.privoxy.org/announce.txt"
		},
		{
			"url": "https://lists.debian.org/debian-lts-announce/2021/03/msg00009.html",
			"description": "MLIST:[debian-lts-announce] 20210309 [SECURITY] [DLA 2587-1] privoxy security update"
		}
	]
}
